### ISSUE TITLE
Can't compile on Debian 9 Stretch

### ISSUE THREAD

**Issue by CocoCocoAlx** [xuminic/ezthumb#1]
I've got this error when I try to compile:
gcc -DHAVE_CONFIG_H -DCFG_GUI_OFF -I.   -I./external/libcsoup -I./external/iup/include 	    -I/usr/include/ffmpeg  -Wall -Wextra -O4 -c -o ezttf.o ezttf.c
ezttf.c:68:22: fatal error: ft2build.h: No such file or directory
 #include <ft2build.h>
                      ^
compilation terminated.

ft2build.h is installed and located in /usr/include/freetype2. What I must do?

Thanks for you time.

**Comment by xuminic** [comment]
Just fixed in the trunk. 
Sorry for the bad delay. I just saw this issue since github didn't send me email notification.

**Comment by samsepiol59** [comment]
I'm still getting the same error, trying to install 3.6.7

**Comment by xuminic** [comment]
Hi, I reviewed the code. It should check the existence of
freetype2/ft2build.h in configure before make a build. Could you post your
logs please?

**Comment by brunomoreno71** [comment]
Ubuntu 16.04: 
apt install libavformat-dev libavcodec-dev libswscale-dev libavutil-dev libgd-dev libfreetype6-dev libpng-dev libjpeg-dev zlib1g-dev 
./configure CPPFLAGS="-I/usr/include/freetype2" 
make
make install

**Comment by xuminic** [comment]
Thanks @brunomoreno71 
The CPPFLAGS="-I/usr/include/freetype2" works pretty well.
